version: "2.3"
services:
  bodypix:
    build:
      context: ./bodypix
      dockerfile: Dockerfile
    image: bodypix
    restart: always
    ports:
      - 9091:9091
    command: node /src/app.js
  fakecam:
    build:
      context: ./fakecam
      dockerfile: Dockerfile
    image: fakecam
    restart: always
    links:
        - bodypix
    command: python fake.py
    environment:
      ACTUAL_CAMERA: "/dev/video0"
      FAKE_CAMERA: "/dev/video20"
      #CAMERA_WIDTH: "640"
      #CAMERA_HEIGHT: "360"
      CAMERA_WIDTH: "1280"
      CAMERA_HEIGHT: "720"
      CAMERA_FPS: "24"
      BODYPIX_URL: http://bodypix:9091
    volumes:
        - ./data:/data
    devices:
        - "/dev/video0:/dev/video0"
        - "/dev/video20:/dev/video20"
networks:
  fakecam:
    driver: bridge
